sudo: required
dist: trusty
services:
- docker
install:
- docker build -t test .
script:
- docker run -ti test /bin/true
- docker run -ti test pkgforge --help
notifications:
  email: false
  slack:
    secure: Ks481f2NgOMEUYxWYBXJINS8o5vktFHb59kyG7dy1mIhesRczfuG1NOCrc2prvHUhdIA3IkALnQ9HBRVgpo2+eF2zA7aavx+eLsCYQzTQ+CbZNrkQL19ZpYL/tSpuUcS2qxyn10yVHDU4kGnZz3E+f1vUuCjIS6bYvIq5VSDLKb+tm4pfWD2KHHCyP9ZBZqJyyQzZM3D1YJArn4/L9jeqzSHR23toX85U+CduZoOXbiV9d1QujoUVm4dMy4ocxtjNZJJzpAQrnFNakyeYGx+xEkNx8FGXBLX538nq+xzN8lgil6TnO4/uxEz0h1sXc04rC0fJ887pk0vkaWX8oaPFO+0pF049depQ2GZ0mnNnqwPLyc6X9a5guAsPZsUHigcgx01Da4MNgHdohmByJDdyJg7E5nuOWzEsUu06aX9vth54kTHKwoksq9oGdPuGTBFdFFhLZg0cw4y+8ehothQubB6wsThvHP41dHigVwcFaAajZRFHe7W0Ve8/YBLykT8r8le8ByAaaFowswSSnmKJBkl/HetbTvy4jLoNzRA/v5S4756fwVuS9WplO8G/MHc4DIcGxczT6D719h4ga87LsXmg7aaujnGul++ZjE8MJQO5whFYzrjWuG5xOEYzC4nNDRvY41DxEVXejRlQQ/6I6dtlJk/M5hktM3TaKUFRLQ=
