name: Build
on: [pull_request, push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: akerl/action-checkout@v2.0.0
    - name: Submodules
      run: git submodule update --init --recursive
    - name: Registry auth
      run: ./meta/login.sh
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Build container
      run: docker build -t new .
    - name: Test container
      run: ./scripts/test.sh
    - name: Publish images
      run: ./meta/publish.sh
      env:
        GITHUB_TOKEN: ${{ github.token }}
        GITHUB_REPO: ${{ github.repository }}
    - name: Notify on success
      if: success()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: akerl/github-action-slack-notify-build@v1.1.1
      with:
        channel_id: ${{ secrets.SLACK_BOT_CHANNEL }}
        status: success
        color: good
    - name: Notify on failure
      if: failure()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: akerl/github-action-slack-notify-build@v1.1.1
      with:
        channel_id: ${{ secrets.SLACK_BOT_CHANNEL }}
        status: failed
        color: danger

